// vars

const callbackFns = [
  'callback',
  'cb',
  'done',
  'next',
  'reject',
  'resolve',
];

const shadowParams = callbackFns.concat([
  'err',
  'error',
  'res',
  'response',
  'req',
  'request',
]);

const paddingOpts = [
  {
    prev: '*',
    next: ['block', 'block-like', 'function', 'return'],
    blankLine: 'always',
  }, {
    prev: ['block', 'block-like', 'function'],
    next: '*',
    blankLine: 'always',
  }, {
    prev: ['const', 'let', 'var'],
    next: ['const', 'let', 'var'],
    blankLine: 'any',
  },
];

// export

module.exports = {
  env: {
    browser: true,
    node: true,
    es2020: true,
  },

  parserOptions: {
    ecmaVersion: new Date().getFullYear(),
    ecmaFeatures: {
      impliedStrict: true,
      globalReturn: false,
    },
  },

  rules: {
    'accessor-pairs': 0,
    'array-bracket-newline': [1, 'consistent'],
    'array-bracket-spacing': [1, 'never'],
    'array-callback-return': [1, {allowImplicit: true}],
    'array-element-newline': [1, 'consistent'],
    'arrow-body-style': 0,
    'arrow-parens': 2,
    'arrow-spacing': 1,
    'block-scoped-var': 2,
    'block-spacing': [1, 'never'],
    'brace-style': 1,
    'callback-return': [2, callbackFns],
    'camelcase': 0, // babel
    'capitalized-comments': 0,
    'class-methods-use-this': 0,
    'comma-dangle': [1, 'always-multiline'],
    'comma-spacing': [1, {before: false, after: true}],
    'comma-style': 1,
    'complexity': [1, {max: 50}],
    'computed-property-spacing': 1,
    'consistent-return': 0,
    'consistent-this': [1, 'self'],
    'constructor-super': 2,
    'curly': [1, 'all'],
    'default-case': 1,
    'default-param-last': 1,
    'dot-location': [1, 'property'],
    'dot-notation': [1, {allowPattern: '^\\w+(_\\w+)+$'}],
    'eol-last': [1, 'always'],
    'eqeqeq': 2,
    'for-direction': 2,
    'func-call-spacing': 1,
    'func-name-matching': [1, 'always', {considerPropertyDescriptor: true}],
    'func-names': [1, 'as-needed'],
    'func-style': [1, 'declaration', {allowArrowFunctions: true}],
    'function-call-argument-newline': [1, 'consistent'],
    'function-paren-newline': [1, 'multiline-arguments'],
    'generator-star-spacing': [1, 'after'],
    'getter-return': [2, {allowImplicit: true}],
    'global-require': 0,
    'grouped-accessor-pairs': [1, 'getBeforeSet'],
    'guard-for-in': 2,
    'handle-callback-err': [1, '^.*(e|E)rr(or)?$'],
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    'implicit-arrow-linebreak': 0,
    'indent': [1, 2, {SwitchCase: 1, flatTernaryExpressions: true}],
    'init-declarations': [1, 'always'],
    'jsx-quotes': [1, 'prefer-double'],
    'key-spacing': 1,
    'keyword-spacing': 1,
    'line-comment-position': 0,
    'linebreak-style': 1,
    'lines-around-comment': [1, {afterBlockComment: true}],
    'lines-between-class-members': [1, 'always', {exceptAfterSingleLine: true}],
    'max-classes-per-file': 0,
    'max-depth': [1, {max: 10}],
    'max-len': 0,
    'max-lines': [1, {max: 1000}],
    'max-lines-per-function': [1, {max: 500}],
    'max-nested-callbacks': [1, {max: 10}],
    'max-params': [1, {max: 10}],
    'max-statements': [1, {max: 250}],
    'max-statements-per-line': [1, {max: 1}],
    'multiline-comment-style': 0,
    'multiline-ternary': 0,
    'new-cap': 0, // babel
    'new-parens': 1,
    'newline-per-chained-call': 0,
    'no-alert': 2,
    'no-array-constructor': 2,
    'no-async-promise-executor': 2,
    'no-await-in-loop': 0,
    'no-bitwise': [1, {int32Hint: true}],
    'no-buffer-constructor': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-class-assign': 2,
    'no-compare-neg-zero': 2,
    'no-cond-assign': 2,
    'no-confusing-arrow': [2, {allowParens: true}],
    'no-console': [1, {allow: ['info', 'warn', 'error']}],
    'no-const-assign': 2,
    'no-constant-condition': 1,
    'no-constructor-return': 2,
    'no-continue': 0,
    'no-control-regex': 1,
    'no-debugger': 2,
    'no-delete-var': 2,
    'no-div-regex': 1,
    'no-dupe-args': 2,
    'no-dupe-class-members': 2,
    'no-dupe-else-if': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-duplicate-imports': [1, {includeExports: true}],
    'no-else-return': 2,
    'no-empty': [2, {allowEmptyCatch: true}],
    'no-empty-character-class': 2,
    'no-empty-function': 1,
    'no-empty-pattern': 2,
    'no-eq-null': 2,
    'no-eval': [2, {allowIndirect: true}],
    'no-ex-assign': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-label': 1,
    'no-extra-parens': 0,
    'no-extra-semi': 1,
    'no-fallthrough': 1,
    'no-floating-decimal': 1,
    'no-func-assign': 2,
    'no-global-assign': 2,
    'no-implicit-coercion': [1, {boolean: false}],
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-import-assign': 2,
    'no-inline-comments': 0,
    'no-inner-declarations': [2, 'both'],
    'no-invalid-regexp': 2,
    'no-invalid-this': 0, // babel
    'no-irregular-whitespace': 2,
    'no-iterator': 2,
    'no-label-var': 2,
    'no-labels': 0,
    'no-lone-blocks': 1,
    'no-lonely-if': 1,
    'no-loop-func': 2,
    'no-loss-of-precision': 2,
    'no-magic-numbers': 0,
    'no-misleading-character-class': 2,
    'no-mixed-operators': 1,
    'no-mixed-requires': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-multi-assign': 1,
    'no-multi-spaces': 1,
    'no-multi-str': 1,
    'no-multiple-empty-lines': [1, {max: 1, maxBOF: 0, maxEOF: 1}],
    'no-negated-condition': 1,
    'no-nested-ternary': 0,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-object': 2,
    'no-new-require': 2,
    'no-new-symbol': 2,
    'no-new-wrappers': 1,
    'no-obj-calls': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 0,
    'no-path-concat': 1,
    'no-plusplus': 0,
    'no-process-env': 0,
    'no-process-exit': 1,
    'no-proto': 2,
    'no-prototype-builtins': 0,
    'no-redeclare': [1, {builtinGlobals: true}],
    'no-regex-spaces': 2,
    'no-restricted-globals': 0,
    'no-restricted-imports': 0,
    'no-restricted-modules': 0,
    'no-restricted-properties': 0,
    'no-restricted-syntax': 0,
    'no-return-assign': 1,
    'no-return-await': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-setter-return': 2,
    'no-sequences': 2,
    'no-shadow': [1, {hoist: 'all', allow: shadowParams}],
    'no-shadow-restricted-names': 2,
    'no-sparse-arrays': 2,
    'no-sync': [1, {allowAtRootLevel: true}],
    'no-tabs': 2,
    'no-template-curly-in-string': 1,
    'no-ternary': 0,
    'no-this-before-super': 2,
    'no-throw-literal': 2,
    'no-trailing-spaces': 1,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-undefined': 0,
    'no-underscore-dangle': 0,
    'no-unexpected-multiline': 2,
    'no-unmodified-loop-condition': 1,
    'no-unneeded-ternary': 1,
    'no-unreachable': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': [2, {enforceForOrderingRelations: true}],
    'no-unused-expressions': 0, // babel
    'no-unused-labels': 1,
    'no-unused-vars': [1, {vars: 'all', args: 'after-used', ignoreRestSiblings: true}],
    'no-use-before-define': [2, {functions: false, variables: false}],
    'no-useless-call': 2,
    'no-useless-catch': 2,
    'no-useless-computed-key': [1, {enforceForClassMembers: true}],
    'no-useless-concat': 1,
    'no-useless-constructor': 1,
    'no-useless-escape': 1,
    'no-useless-rename': 1,
    'no-useless-return': 1,
    'no-var': 2,
    'no-void': 1,
    'no-warning-comments': 0,
    'no-whitespace-before-property': 1,
    'no-with': 2,
    'nonblock-statement-body-position': 1,
    'object-curly-newline': [1, {multiline: true, consistent: true}],
    'object-curly-spacing': 0, // babel
    'object-property-newline': [1, {allowAllPropertiesOnSameLine: true}],
    'object-shorthand': [1, 'always', {avoidExplicitReturnArrows: true}],
    'one-var': [1, 'never'],
    'one-var-declaration-per-line': 0,
    'operator-assignment': 0,
    'operator-linebreak': [1, 'after'],
    'padded-blocks': [1, 'never'],
    'padding-line-between-statements': [1, ...paddingOpts],
    'prefer-arrow-callback': 1,
    'prefer-const': 1,
    'prefer-destructuring': 0,
    'prefer-exponentiation-operator': 1,
    'prefer-named-capture-group': 0,
    'prefer-numeric-literals': 2,
    'prefer-object-spread': 1,
    'prefer-promise-reject-errors': 2,
    'prefer-regex-literals': 1,
    'prefer-rest-params': 1,
    'prefer-spread': 1,
    'prefer-template': 1,
    'quote-props': [1, 'consistent-as-needed'],
    'quotes': 0, // babel
    'radix': [2, 'as-needed'],
    'require-atomic-updates': 0,
    'require-await': 0,
    'require-unicode-regexp': 0,
    'require-yield': 2,
    'rest-spread-spacing': [2, 'never'],
    'semi': 0, // babel
    'semi-spacing': 1,
    'semi-style': 1,
    'sort-imports': 0,
    'sort-keys': 0,
    'sort-vars': [1, {ignoreCase: true}],
    'space-before-blocks': 1,
    'space-before-function-paren': [1, {named: 'never'}],
    'space-in-parens': [1, 'never'],
    'space-infix-ops': [1, {int32Hint: true}],
    'space-unary-ops': [1, {words: true, nonwords: false}],
    'spaced-comment': [1, 'always', {markers: ['/'], block: {balanced: true}}],
    'strict': [2, 'never'],
    'switch-colon-spacing': 1,
    'symbol-description': 1,
    'template-curly-spacing': [1, 'never'],
    'template-tag-spacing': [1, 'never'],
    'unicode-bom': 2,
    'use-isnan': 2,
    'valid-typeof': 0, // babel
    'vars-on-top': 0,
    'wrap-iife': 2,
    'wrap-regex': 1,
    'yield-star-spacing': [2, 'after'],
    'yoda': [2, 'never'],
  },
};
