// export

module.exports = {
  plugins: ['lodash'],

  rules: {
    'lodash/callback-binding': 2,
    'lodash/chain-style': [1, 'as-needed'],
    'lodash/chaining': [2, 'never'],
    'lodash/collection-method-value': 2,
    'lodash/collection-ordering': [1, {method: 'orderBy', useArray: 'as-needed'}],
    'lodash/collection-return': 2,
    'lodash/consistent-compose': [1, 'flow'],
    'lodash/identity-shorthand': [1, 'always'],
    'lodash/import-scope': 0,
    'lodash/matches-prop-shorthand': [1, 'always'],
    'lodash/matches-shorthand': [1, 'always'],
    'lodash/no-commit': 2,
    'lodash/no-double-unwrap': 2,
    'lodash/no-extra-args': 2,
    'lodash/no-unbound-this': 2,
    'lodash/path-style': 0,
    'lodash/prefer-compact': 1,
    'lodash/prefer-constant': 1,
    'lodash/prefer-filter': 1,
    'lodash/prefer-find': 1,
    'lodash/prefer-flat-map': 1,
    'lodash/prefer-get': 1,
    'lodash/prefer-immutable-method': 1,
    'lodash/prefer-includes': [1, {includeNative: false}],
    'lodash/prefer-invoke-map': 1,
    'lodash/prefer-is-nil': 1,
    'lodash/prefer-lodash-chain': 2,
    'lodash/prefer-lodash-method': 0,
    'lodash/prefer-lodash-typecheck': 1,
    'lodash/prefer-map': 1,
    'lodash/prefer-matches': 1,
    'lodash/prefer-noop': 1,
    'lodash/prefer-over-quantifier': 1,
    'lodash/prefer-reject': 1,
    'lodash/prefer-some': [1, {includeNative: false}],
    'lodash/prefer-startswith': 1,
    'lodash/prefer-thru': 1,
    'lodash/prefer-times': 1,
    'lodash/prefer-wrapper-method': 1,
    'lodash/preferred-alias': 1,
    'lodash/prop-shorthand': 1,
    'lodash/unwrap': 2,
  },
};
